sudo: required
services: 
  - docker
before_install:
  - docker build -t jakewilson780/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true jakewilson780/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-east-2-585906208485"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"